### ISSUE TITLE
The Influence of PCR duplicates on Arcs

### ISSUE THREAD

**Issue by danshu** [bcgsc/arcs#10]
Hi,

I found that chromium sequencing have more bias (GC bias, PCR duplicates) than standard WGS. In the manuscript, it mentioned that:
These form a link between the two sequences, provided that there is sufficient number of read pairs aligned (-c, set to 5 by default)
So I wonder if ARCs will consider PCR duplicates during scaffolding. If not, is it better to remove duplicates before scaffolding using Arcs?

Best,
Danshu

**Comment by danshu** [comment]
After carefully reading the manuscript, I have a few further questions.

1. For parameter -e and -z, if -e is 30kb and -z is 1kb, so for a contig of length 2kb, its H and T regions are both the entire sequences?
2. It is mentioned in the manuscript that adjusting -e to a lower value to account for shorter contigs is important. Does this means that I should adjust -e according to N50 of my assembly? The genome size of my target species is less than one tenth of the human genome size, so do I have to adjust -e accordingly?
3. "These form a link between the two sequences, provided that there is sufficient number of read pairs aligned (-c, set to 5 by default)." By 5 read pairs do you mean that there are at least 5 read pairs of that barcode mapped to one contig and at least 5 read pairs mapped to another contig? Does Arcs consider whether some of these 5 read pairs are due to duplicates (such as PCR duplicates)?
4. "For a given barcode to contribute linking evidence, the distribution of reads of that barcode aligning to the H or T regions of both sequences in the potential pair must significantly differ from a uniform distribution". I do not quite understand this.
5. "Ambiguous pairings are resolved when the ratio of barcode links of the second-most to top-most supported edge is equal or below a threshold (LINKS parameter -a, default of 0.3; we recommend higher values such as -a 0.7 and 0.9 when running LINKS within ARCS)". For -a=0.9, do you think that the link orientation with the maximum support is predominant?

Best,
Danshu

**Comment by sarahyeo** [comment]
Hi Danshu,

1. In this case (when contig length is < 1/2 of -e) we split the contig in half by length, and label each region H or T. Thus in your example, both H and T regions would be 1kb.

2. Yes this may be a good idea to try. However you may need to lower -c as well if you lower -e to account for the shorter H/T regions being considered.

3. Yes we mean there at least 5 read pairs mapped to contig A and at least 5 mapped to contig B. Only primary alignments are considered. ARCS is not PCR-duplicate aware. 

4. We do not consider barcodes that have an even distribution of reads aligning to both the H and T (ex. 7 read pairs aligning to H and 6 read pairs aligning to T). This is because it does not provide us with enough information to orient the contig. We use a binomial test to determine if the distribution of reads differs significantly from a uniform distribution.

5. Yes, the most predominant linkage is always chosen, regardless of the link ratio (note that the link ratio -a may prevent scaffolding even when linkages are abundant).

Thanks,
Sarah

**Comment by danshu** [comment]
Hi Sarah,

Thanks for your explanation which is very useful!

Best,
Danshu
