### ISSUE TITLE
No scaffolding

### ISSUE THREAD

**Issue by mlcossette9224** [bcgsc/arcs#103]
I finished running my arcs-links script and have the same number of scaffolds in the final .fa file than the number of contigs in my original assembly file. 

Any idea of what could have gone wrong?

I did use long ranger basic on my reads.

This is what I have ran
> perl -ne 'chomp; if(/>/){$ct+=1; print ">$ct\n";}else{print "$_\n";} ' < myassembly.fa > myassembly.renamed.fa 
>
> touch empty.fof
>
> bwa index -p index myassembly.renamed.fa 
> 
> sh -c 'bwa mem -t32 -C -p myassembly.renamed.fa myreads.fq.gz | samtools view -Sb - | samtools sort -@32 -n - -o myassembly.sorted.bam'
> 
> echo myassembly.sorted.bam > myassembly_bamfiles.fof
> 
> arcs -f myassembly.renamed.fa -a myassembly_bamfiles.fof -v -c 5 -m 50-10000 -s 98 -r 0.05 -e 30000 -z 500 -d 0 --gap 100 -b myassembly_c5_m50-10000_s98_r0.05_e30000_z500 --barcode-counts barcodeMultiplicityArcs.tsv
> 
> python makeTSVfile.py myassembly_c5_m50-10000_s98_r0.05_e30000_z500_original.gv myassembly_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv myassembly.renamed.fa 
> 
> ln -s myassembly_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
> 
> LINKS -f myassembly.renamed.fa -s empty.fof -b myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3 -l 5 -a 0.3 -z 500

Thanks

**Comment by lcoombe** [comment]
Hello @mlcossette9224,

Just a couple of follow-up questions to help with troubleshooting:
* Did you run the above using the `arcs-make` Makefile? If so, could you include your command? Or did you just run a shell script with each of these steps?
* Was your graph file (`*original.gv`) empty? Or did it have many nodes/edges?

Thanks!
Lauren

**Comment by mlcossette9224** [comment]
Hi Lauren,

Thanks for the quick response!
I am using the loaded module on a cluster so I don't have the option to use the arcs-make file.
My *original.gv looks like this if I head it

> graph G {
> 0 [id=100900];
> 1 [id=100901];
> 2 [id=102452];
> 3 [id=193717];
> 4 [id=103214];
> 5 [id=103215];
> 6 [id=105950];
> 7 [id=206548];
> 8 [id=106790];

**Comment by lcoombe** [comment]
Interesting -- so it isn't an empty graph file (which is a common issue). Could you also do a quick head of the `myassembly_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv`file? Also, would it be possible to see the full log of your run?

What is the contiguity of your base assembly, and what is your coverage of linked reads?

A couple of parameters that you could play with:
* `z`: Try increasing it to say 1kb -- sometimes too many small pieces can make the graph too complicated and prevent joins
* `a`: Increase up to 0.9 - this decreases the stringency of the scaffolding decisions
* `l`: Decrease it, again to reduce stringency
Do note that to play with these parameters, you only have to re-run the LINKS stage, not all the previous stages.

Hopefully playing around with some of those parameters would help us to at least understand if this is due to a parameter issue (with your linked reads and the assembly) or if it's an issue with the commands - I don't see anything obvious that is wrong with your commands.

Lauren

**Comment by mlcossette9224** [comment]
Head of the tigpair_checkpoint.tsv looks like this but only has 434 lines, could this be an issue? I have seen other people’s tigpair_checkpoint.tsv which had a lot more entries.

> 10	f100900	f100901	3	300
> 10	r100901	r100900	3	300
> 10	r102452	r193717	3	300
> 10	f193717	f102452	3	300
> 10	f103214	f103215	3	300
> 10	r103215	r103214	3	300
> 10	r105950	f206548	4	400
> 10	r206548	f105950	4	400
> 10	f106790	f49590	3	300
> 10	r49590	r106790	3	300

Here are the logs for the arcs and links runs

Arcs
> Reading user inputs...
> Finished reading user inputs...entering runArcs()...
> Running: arcs 1.2.0
> ARCS method
>  pid 13949
>  -c 5
>  -d 0
>  -e 30000
>  -l 0
>  -m 50-10000
>  -r 0.05
>  -v 1
>  -z 500
>  --gap=100
>  -s 98
>  -b myassembly_c5_m50-10000_s98_r0.05_e30000_z500
>  -g myassembly_c5_m50-10000_s98_r0.05_e30000_z500.dist.gv
>  --barcode-counts=barcodeMultiplicityArcs.tsv
>  --tsv=myassembly_c5_m50-10000_s98_r0.05_e30000_z500_main.tsv
>  -a myassembly_bamfiles.fof
>  -f myassembly.renamed.fa
>  -u NA
>  myassembly.sorted.bam
> 
> => Getting scaffold sizes... Tue Jan 26 08:53:22 2021
> Saw 491292 sequences.
> 
> => Reading alignment files... Tue Jan 26 08:53:32 2021
> Reading alignments: myassembly.sorted.bam
> On line 10000000
> On line 20000000
> On line 30000000
> On line 40000000
> On line 50000000
> On line 60000000
> On line 70000000
> On line 80000000
> On line 90000000
> On line 100000000
> On line 110000000
> On line 120000000
> On line 130000000
> On line 140000000
> On line 150000000
> On line 160000000
> On line 170000000
> On line 180000000
> On line 190000000
> On line 200000000
> On line 210000000
> On line 220000000
> On line 230000000
> On line 240000000
> On line 250000000
> On line 260000000
> On line 270000000
> On line 280000000
> On line 290000000
> On line 300000000
> On line 310000000
> On line 320000000
> On line 330000000
> On line 340000000
> On line 350000000
> On line 360000000
> On line 370000000
> On line 380000000
> On line 390000000
> On line 400000000
> On line 410000000
> On line 420000000
> On line 430000000
> On line 440000000
> On line 450000000
> On line 460000000
> On line 470000000
> On line 480000000
> On line 490000000
> On line 500000000
> On line 510000000
> On line 520000000
> On line 530000000
> On line 540000000
> On line 550000000
> On line 560000000
> On line 570000000
> On line 580000000
> On line 590000000
> On line 600000000
> On line 610000000
> On line 620000000
> On line 630000000
> On line 640000000
> On line 650000000
> On line 660000000
> On line 670000000
> On line 680000000
> On line 690000000
> On line 700000000
> On line 710000000
> On line 720000000
> Cumulative memory usage: 9927772
> 
> Pairing scaffolds... Tue Jan 26 11:00:09 2021
> Creating the graph... Tue Jan 26 11:11:53 2021
> 
> Writing graph file... Tue Jan 26 11:11:53 2021
> 
>       Max Degree (-d) set to: 0. Will not delete any vertices from graph.
>       Writing graph file to myassembly_c5_m50-10000_s98_r0.05_e30000_z500_original.gv...
> 
> Creating the ABySS graph... Tue Jan 26 11:11:53 2021
> 
> Writing the ABySS graph file... Tue Jan 26 11:11:54 2021
> 
> { "All_barcodes_unfiltered":2436302, "All_barcodes_filtered":1407515, "Scaffold_end_barcodes":1829453, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }
>
> Writing TSV file... Tue Jan 26 11:11:55 2021
>
> Writing reads per barcode TSV file... Tue Jan 26 11:12:14 2021
>
> Done.
> Tue Jan 26 11:12:20 2021

LINKS

> Running: /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/links/1.8.6/bin/LINKS [v1.8.6]
> -f myassembly.renamed.fa
> -s empty.fof
> -m 
> -d 4000
> -k 15
> -e 0.1
> -l 5
> -a 0.3
> -t 2
> -o 0
> -z 500
> -b myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3
> -r 
> -p 0.001
> -x 0
> 
> ----------------- Verifying files -----------------
> 
> Checking sequence target file myassembly.renamed.fa...ok
> 
> 
> Scaffolding mid-point files:
> myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
> myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.simplepair_checkpoint.tsv
> detected; LINKS will skip contig pairing and use info from files instead : Tue Jan 26 11:19:19 EST 2021
> 
> Reading sequences from myassembly.renamed.fa : Tue Jan 26 11:19:19 EST 2021
> 
> done.
> Reading sequence pairs from myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv : Tue Jan 26 11:19:32 EST 2021
> 
> done.
> Building scaffolds : Tue Jan 26 11:19:32 EST 2021
> 
> done.
> Building .gv graph : Tue Jan 26 11:19:38 EST 2021
> 
> 
> =>Scaffolding ended : Tue Jan 26 11:19:38 EST 2021
> Scaffolds layout in: myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds
> Scaffold graph in: myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.gv
> 
> 
> =>Making FASTA file : Tue Jan 26 11:19:38 EST 2021
> Scaffolds FASTA in : myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa
> 
> 
> =>Wrote correspondence file tracking LINKScontigID <=> OriginalContigNames : myassembly_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.assembly_correspondence.tsv


My linked reads have a coverage of 24.20

I am using contigs generated by Meraculous
Contig N50 = 5614
Config N90 = 1846
#final contigs = 491,292
102,052 contigs > 5.6 Kb
Genome is about 3Gb

Thanks! I will try with new parameters

**Comment by mlcossette9224** [comment]
I just adjusts the parameters to -l 2 -a 0.9 -z 1000 and there is a slight difference.

Original parameters
> sum = 1872879414, n = 491262, ave = 3812.38, largest = 73774
> N50 = 5614, n = 102022
> N60 = 4568, n = 139020
> N70 = 3635, n = 184927
> N80 = 2754, n = 243955
> N90 = 1846, n = 326265
> N100 = 54, n = 491262
> N_count = 3000
> Gaps = 30

New parameters
> sum = 1872898114, n = 491075, ave = 3813.87, largest = 90171
> N50 = 5615, n = 101835
> N60 = 4568, n = 138832
> N70 = 3635, n = 184738
> N80 = 2754, n = 243767
> N90 = 1846, n = 326077
> N100 = 54, n = 491075
> N_count = 21700
> Gaps = 217

**Comment by lcoombe** [comment]
I'm glad that you are least getting some joins now! I think a couple of issues here are your somewhat low coverage of linked reads, and an assembly with a fairly low contiguity. ARCS tends to perform best on assemblies that are more contiguous.

Another parameter that you could tweak, but it's at the `arcs` step is `c` -- this is the number of read pairs mapping to a contig end for a barcode to 'hit' to that end. It's possible that the default of `5` is too stringent given the contiguity of your assembly.

So the good news is that your commands look fine, but I think some parameter sweeps might be needed for you to see the best results!

**Comment by mlcossette9224** [comment]
Thanks!

**Comment by RNieuwenhuis** [comment]
Hi @lcoombe  , 

I am jumping into this thread because I have a similar situation and the suggestions you have given so far are working very well. Especially the `c` parameter.

However could you maybe explain the `e` parameter as well and how this affects the scaffolding. I was under the impression that _decreasing_ it may improve scaffolding of smaller fragments, because you would get more mapped reads that count as evidence for links. However, so far I decreased it to 3000 and see almost no result in scaffolding. That seems counterintuitive to me. Did I misunderstood this command line option?

**Comment by lcoombe** [comment]
Hi @RNieuwenhuis,

I'm glad the suggestions are working for you!

The `e` parameter specifies the head/tail length of the contigs - that is the length of sequence at the beginning and the end of each contig where look for barcode hits (either through alignments in default ARCS mode, or exact k-mer matching in ARKS mode). If a given contig is shorter than 2xcontig_length, then the head/tail lengths are just each the first and last half of the contig, respectively.
So decreasing the parameter wouldn't actually necessarily increase the number of mapping reads that count towards barcode hits -- in some cases it wouldn't impact the number of barcode hits (smaller pieces), or could decrease the number of hits (larger pieces). On the other hand, there are checks to see if the distribution of barcode hits to a contig is significantly different from a uniform distribution, so changing the `e` parameter, could improve barcode hits in that way. So I guess the short answer is that it depends!

We don't play around with the `e` parameter too much, since we generally find that the default performs pretty well, but if I was going to do a sweep I probably would keep the value 10,000-50,000 -- upper bound being roughly the average molecule size of linked read libraries, and not going too small to ensure that we are getting multiple read pairs from the same barcode mapping to contig ends.

Hope that helps!
Lauren

**Comment by RNieuwenhuis** [comment]
Thanks for clarifying that @lcoombe , now I understand.
