### ISSUE TITLE
Could not open @HD      VN:1.3  SO:coordinate. --fatal

### ISSUE THREAD

**Issue by shameem356** [bcgsc/arcs#11]
Hello,

I am trying to run arcs with bam file (generated by 10x longranger align).But getting the following error. below is the command which I used for running arcs 

command : 
arcs -f genome.fa -a possorted_bam.bam -b arcs_out

**Error** : 
-------
=>Getting scaffold sizes... Sun Feb 26 17:16:31 2017
=>Starting to read BAM files... Sun Feb 26 17:16:36 2017
Could not open @HD      VN:1.3  SO:coordinate. --fatal.

**Comment by warrenlr** [comment]
I believe this is due to read names having "spaces".
You will have to re-generate the alignments, by carefully following the instructions provided here:
Documentation:

https://github.com/bcgsc/ARCS/
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs/arcsDemoScripts/readme.md




We have also created a test demo (you can look at example bam files provided).

download:
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs/arcs_test-demo.tar

and follow the instructions in the README.txt

**Comment by smg283** [comment]
Is your FTP down?  I can't seem to access the links you provided through wget or ftp

**Comment by warrenlr** [comment]
the ftp appears to be working internally. I will inquire and get back to you about external access.

**Comment by shameem356** [comment]
Not able to download the test data from ftp.please can you check it

**Comment by warrenlr** [comment]
we have been having trouble with our ftp lately. It works internally now (Monday March 20th 7:12 PST)
Do you get a session timeout?  alternatively, could you post the error message?
thanks,
Rene

**Comment by warrenlr** [comment]
external access to ftp.bcgsc.ca seems to be working again.
