### ISSUE TITLE
arcs-long: tiny PE-pairs are produced

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/arcs#121]
Hi,
  I am trying to figure out why the file with fake PE read-pairs derived from my nanopore reads contains e.g.:

```
@4d49bce6-483f-4824-8f66-ec01b60ca981_f5 BX:Z:57
AAACTGGA
+
########
@4d49bce6-483f-4824-8f66-ec01b60ca981_f5 BX:Z:57
TCCAGTTT
+
########
```

   The source read was 2008 bases long. It seems `long-to-linked-pe` walks from left and picks 250 bases for the first F1 read, then skips 250 bases, then picks another 250 for the second F1 read, and so on. It gets tricky as it reaches the righ end of the read. In this case, the F4 read was 250+250+8 bases before the 3'-end. The problematic F5 read is hown above and was just the 8 bases. I guess this dampens efectiveness of the ar[ck]s-long approach as the links on the 3'-end of read may not have enough good links.

1.   I think it would be better for the last fake read pair to walk in the 3'- to 5' direction.

  Otherwise, `long-to-linked-pe` could at least discard the short remainder of the sequence. In my case, it was not 8 bases but 258 bases, which was good enough IMO. We have exons spanning probably around 120 bases on average so discarding a 258 bases from the end of a read seems quite wasteful. Hence just dropping the tiny PE-pair members is not a proper solution for me.

2.   Would you mind including on the webpage a graphical scheme how you create the fake read-pairs? What is the distance between them? (I mean PE insert-size in terminology of wet-lab).

  What is also difficult to understand to me what happens if the contigs to be assembled end (typically?) in low-complexity or repeat sequences. It must be difficult to get a unique match on such ends. Such contigs could be incorporated only thanks to links hitting some more uniqie sequence in their internal regions. At a first glance it seems to me I should go for longer fake PE read sizes, like 2x500 or even 2x1000. (I saw the parameters `z` and `e` briefly discussed under https://github.com/bcgsc/arcs/issues/103 , btw).

**Comment by lcoombe** [comment]
Hi @mmokrejs,

Yes, that's right, when simulating the pseudo-linked reads if the end is not divisible by the fragment length (2 x read_length), you could end up with shorter sequences at the end of a long read. Think of it like taking tiles of the fragment length, then using that fragment to make paired-end reads with no distance between them (----> <----). Certainly, we can add a diagram if that would help to understand the simulation.

Have you seen this shorter read pair leading to erroneous joins/results? If so, could you share those? I wouldn't have thought that this stray read pair would have much impact on the results either way. If the concern is that it could cause erroneous mappings, remember that ARCS requires at least `-c` read pairs mapping to a contig end before it considers that a 'barcode hit'. Therefore, only this read pair aligning to a different contig end shouldn't lead to a possible edge in the scaffold graph. 

I'm hesitant to implement your (1) - that is biasing the distribution of the read pairs to the end sequence a bit - you end up with largely overlapping fragments at the end. Your concern about dropping reads was shared by us, and is why we left the code in it's current state - the shorter fragment at the end could contribute signal, but isn't a big problem if it doesn't since it's such a short bit. In fact, it's not uncommon to trim regular Illumina/linked reads, which could similarly lead to quite short reads.

As for your question about repeats at the sequence ends, yes, unique sequence would be needed to make a confident join. The length of the reads/molecules are what helps there - that in most cases the evidence will be long enough to read to a more unique region, and thus allow for scaffolding evidence. If the repeat at an end was longer than the read lengths, then it's possible that a potential join could be missed.

We found that we got the best results when using read length = 250bp, but of course that is a length you could play around with. The results were not vastly different in our tests with longer read lengths.

Lauren

**Comment by lcoombe** [comment]
Pseudo-linked read diagram added in #142
