### ISSUE TITLE
Scaffolding Expectations

### ISSUE THREAD

**Issue by aakashsur** [bcgsc/arcs#141]
Hi, 

 I looked through a few of the other issues regarding tuning scaffolding parameters but I wanted to make sure I have a good handle on the parameters and the expectations for improvement. Here's our dataset - 

**Assembly**  
5,913 sequences
902,328,951 bp total length
2,211,090 bp largest contig
397,011 bp N50

**Linked Reads**
270,669,346 interleaved reads
64,825,308,367 bp
72x coverage of assembly

Here are the parameters we have used are the results we get. 

1) Default

5,901 sequences
2,211,090 bp largest contig
399,206 bp N50

2) arcs -c 2 -s 98 -z 1000 / links -l 2 -z 1000

5,735 sequences
2,211,090 bp largest contig
428,811 bp N50

3) arcs -c 2 -s 90 -z 1000 / links -l 2 -a 0.5 -z 1000

5,233 sequences
3,313,861 bp largest contig
549,077 bp N50

4) arcs -c 2 -s 90  -z 5000 / links -l 2 -a 0.9 -z 5000

5,180 sequences
902,402,251 bp total length
3,313,861 bp largest contig
564,264 bp N50

**Questions**
1) Are these a reasonable set of parameters to test? Have the values I've used gone beyond the recommend range, and maybe I'm getting longer assemblies but they won't be trustworthy?  Are there other parameter sets we should test? 

2) What is the relationship between `arcs -c` and `links -l`? Should they be set to the same value? 

3) What kind of improvements should we expect from a dataset like this? Is what we got about what you might expect, or should we have gotten better scaffolding? 

For reference on the commands we are using, this is the structure: 

```
arcs \
    -f assembly.renamed.fa \
    -a bamfiles.fof \
    -v \
    -c 2 \
    -s 90 \
    -z 1000 \
    -b assembly \
    --barcode-counts assembly.tsv

python /sw/contrib/stf-src/arcs/1.2.1/build/Examples/makeTSVfile.py \
    assembly_original.gv \
    assembly.tigpair_checkpoint.tsv \
    assembly.renamed.fa

LINKS \
    -f assembly.renamed.fa \
    -s empty.fof \
    -l 2 \
    -a 0.5 \
    -z 1000 \
    -b assembly
```

**Comment by lcoombe** [comment]
Hi @aakashsur,

1. Yes, those look like reasonable parameters. I would not go lower for the sequence identity than 90, but you would still be keeping fairly high quality alignments there. You are on the less stringent side for the parameters (c, l, a), but not in an unreasonable range. Have you looked at the barcode multiplicity distribution of your linked reads? The range accepted is specified by `-m`, but you could look at this distribution for your data (number of barcodes per read) to see if the default range is appropriate for your data.

2. The `arcs -c` parameter specifies the minimum number of read pairs from a barcode aligning to a contig end to consider a 'barcode hit'. For example, as you have it now, if 2 read pairs with BX:Z:1 align to the 'tail' region of ctg1, then BX:Z:1 would 'hit' to the tail of ctg1. The `links -l` parameter controls the minimum of barcode links between sequences in the scaffold graph. So, with your current setting, you require at least 2 barcodes joining sequences for those to be considered to join. They don't need to be set to the same value.

3. It's hard to say what improvement to expect not knowing the quality of the input assembly or data. I would have expected slightly better scaffolding with the default parameters than you showed, but there are lots of different things in play with different assemblies. Have you tried running Tigmint prior to the ARCS run? We often recommend that because breaking misassemblies (with Tigmint) can then allow better scaffolding with ARCS.

Hope that helps - thank you for your interest in ARCS!
Lauren

**Comment by aakashsur** [comment]
Lauren, 

 Thanks for the detailed response.

1) Here's a plot of my barcode multiplicity - 

<img src="https://user-images.githubusercontent.com/7614271/150890635-d3585da4-c674-4471-b5e9-2f3a030b7361.png" width="600" height="500">

<img src="https://user-images.githubusercontent.com/7614271/150890675-7bb12cca-97a6-432b-8d91-38f6fa1a3dd7.png" width="600" height="500">

 Any suggestions on what to set `-m` to? 

2) Do you suggest some relationship between the `arcs -c` and `arcs -l`? Should they be the same value, or one should be greater than the other? 

3) I'll try out tigmint!

Thanks,

**Comment by lcoombe** [comment]
Hi @aakashsur,

1. Based on the histogram, I'd try changing the range to say `30-5000` - Not sure if it'll make a big difference or not, but worth a try, and I'd be interested to hear how much it changes the assemblies. It's possible that using `50` as the lower number of the range was excluding a number of good barcodes, based on your histogram. 

2. For `-c` and `-l`, I generally use values 2-5 and 3-5, respectively. Their settings don't need to be related in any way - you could sweep them independently. That's because `-c` influences the barcode hits to contig ends, while `-l` influences the minimum required barcodes supporting a given edge.

3. Awesome - good luck!

**Comment by aakashsur** [comment]
Just to follow-up, I've completed a run with default tigmint settings and it looks like it decreased our N50 a fair bit. The obvious reaction as that the input assembly had a lot of errors, though I suppose it could be a matter of tuning the parameters on tigmint. 

**Assembly**
5,913 sequences
902,328,951 bp total length
2,211,090 bp largest contig
397,011 bp N50

**After Tigmint**
44,903 sequences
435,978 bp largest contig
62,372 bp N50

**After Arcs/Links -c 2 -m 30-5000 -z 1000 -s 95 -l 3 -a 0.9**
42,976 sequences
739,209 bp largest contig
80,192 bp N50

I think the last thing to try would be to skip tigmint and just try arcs/links again with more allowance on the `-m` parameter.

**Comment by lcoombe** [comment]
Hi @aakashsur,
What parameters did you use for Tigmint? An option would be to make the cutting less strict - you can adjust that with the `span` parameter. For example, trying `span=2, 5, 10`. The nice thing about that would be that it would be fast to try since Tigmint is based on a Makefile, and the `span` parameter only impacts a post-alignment step. So, if you run the commands with different `span` values in the same working directory, you should see the program starting at the `tigmint-cut` stage.
If you still see a drastic drop in the N50, then it would make sense to skip Tigmint - Here and there I have seen that behaviour for assemblies, but it's not the norm. Another good metric to add in would be BUSCOs - sometimes you can see BUSCOs are higher in assemblies that are less contiguous if they are indeed more correct.

**Comment by aakashsur** [comment]
I believe I used the default option, here is the command I used - 

```
arcs-make arcs-tigmint \
	draft=masurca_corrected_matepair \
	reads=egracilis_10x \
	time=1 \
	t=40 \
	c=2 \
	m=30-5000 \
	z=1000 \
	s=95 \
	l=3 \
	a=0.9
```

I'm curious what the recommend way of running tigmint + arcs is, as the tigmint docs suggest `tigmint-make arcs` and the `arcs-make help` suggests `arcs-make arcs-tigmint`. My assumption was that they are the same. 

I'll be sure to try the different span parameters and let you know. We do use Busco a fair bit, but I haven't run it during the scaffolding optimization phase so that's a good idea, thanks!

**Comment by aakashsur** [comment]
An update on the `-m` parameter for us, it looks like there isn't any noticeable difference. Parameters - 

1. **-m 50-5000** (arcs -c 2 -s 95  -z 1000 -m 50-5000 / links  -l 3 -a 0.9 -z 1000) 
5,504 sequences
3,313,861 bp largest contig
477,279 bp N50

2. **-m 30-5000** (arcs -c 2 -s 95  -z 1000 -m 30-5000 / links  -l 3 -a 0.9 -z 1000) 
5,504 sequences
3,313,861 bp largest contig
477,279 bp N50

3. **-m 20-5000** (arcs -c 2 -s 95  -z 1000 -m 20-5000 / links  -l 3 -a 0.9 -z 1000) 
5,504 sequences
3,313,861 bp largest contig
477,279 bp N50

**Comment by aakashsur** [comment]
An update on the `span` parameter of tigmint. I ran BUSCO as well (eukaryota). Parameters - 

**original** 
5,913 sequences
2,211,090 bp largest contig
397,011 bp N50
154 missing BUSCOs

**span 2**
36,795 sequences
551,044 bp largest contig
99,542 bp N50
155 missing BUSCOs

**span 5**
42,166 sequences
473,999 bp largest contig
79,686 bp N50
156 missing BUSCOs

**span 10**
43,600 sequences
455,973 bp largest contig
71,892 bp N50
157 missing BUSCOs

**span 20** 
44,903 sequences
435,978 bp largest contig
62,372 bp N50
156 missing BUSCOs

I could try arcs with the lower span settings, maybe 2 and 5 and see what we get back.

**Comment by lcoombe** [comment]
Hi @aakashsur,

Those are interesting results - you aren't losing more BUSCOs really with any of the spans. Do you see a different trend with complete BUSCOs? It's possible if you also still see the BUSCOs remaining steady that the cuts are largely at true misassembled regions - perhaps the baseline assembly has more misassemblies?
Can I ask how the baseline assembly was generated? The main time I can recall us noticing that Tigmint breaks apart assemblies more than expected is for Supernova assemblies - we believe due to the very large gap sizes that that assembler can generate.

Regardless, quite understandable if you want to skip Tigmint given the contiguity results you are seeing - it's still possible that the final Tigmint+ARCS assembly is more correct, but as we mentioned we really only have BUSCOs as a proxy for that, so it's more difficult to know when you don't have a reference.

**Comment by aakashsur** [comment]
There is a very similar trend with complete BUSCOs. I do agree that the cuts could definitely be in regions that are misassembled or low complexity.

We are trying to assembly E. gracilis which is a single cell algae species that has been quite challenging to solve historically. I assume it's because there is a) a lot of repeats, b)  probably a lot of genetic invaders like viruses and retrotransposons, and c) it has an evolutionary history of eating and integrating other species into its genome. 

Here's an overview of our dataset - 
1) Illumina (284,171,620 reads / 53x coverage)
2) PacBio (3,936,611 reads / 44x coverage)
3) Nanopore (410,593 reads / 2x coverage)
4) 10x Linked (270,669,346 reads / 81x coverage)
5) Hi-C (451,398,791 reads / 85x coverage)
6) Matepair (36,182,723 reads / 5x coverage)

Our best assemblies came by error correcting our long read data with short reads, then running Canu or Masurca. The Masurca assembler can use matepairs and that's what produced this particular assembly. On average we get between 20kb - 80kb N50s through the process, but using corrected long reads and matepairs with Masurca produced a particularly long assembly with a 400kb N50. Unfortunately our Hi-C data isn't great so I think we'll get limited use out of that. I think we may skip tigmint since in theory our N50 boost is from matepair evidence, but I'll see how the tigmint-long goes as well.

**Comment by lcoombe** [comment]
Oh very interesting! The only comparator I could give is our assemblies of spruce genomes, which are very repetitive (as well as large) - we also got the best assembly with long reads, but do find we can improve upon that with LongStitch, Tigmint and ARCS (when we had both long read and linked read).

Good luck with Tigmint-long!

**Comment by aakashsur** [comment]
Thanks, I'll probably post an update once that finishes. I'll go ahead and close the issue.
