### ISSUE TITLE
Running ARCS and ARKS

### ISSUE THREAD

**Issue by aakashsur** [bcgsc/arcs#143]
I was wondering how it might work to use both ARCS and ARKS. We have both a 10x library, the original long reads we used for the assembly. I saw LongStitch was another of your projects so I was wondering if you would suggest using ARCS first and then ARKS, the other way around, or just use ARCS since we have already used the long reads in the _de novo_ assembly process? 

Sorry for the loads of questions!

**Comment by lcoombe** [comment]
Hi @aakashsur,

Good question! If you have both long reads and linked reads, I would suggest running LongStitch first (using the long reads), then ARCS/ARKS.

To be clear (it's a bit confusing), ARCS and ARKS largely share a codebase, the only difference is how the reads are mapped to contigs. So for linked reads, you could use ARCS _or_ ARKS. ARKS tends to be faster then ARCS, but will give similar scaffolding results.

Within LongStitch, we introduced ARCS-long/ARKS-long - which is an adaptation of our original ARCS code to use long reads instead of linked reads. In LongStitch, we use ARKS-long. Note that the default mode of LongStitch is to run Tigmint-long+ntLink, but you can easily additionally run ARKS-long by specifying that target (see the LongStitch README for details).

With that all said, if you do have long reads I'd suggest:
LongStitch (Tigmint-long + ntLink + ARKS-long) with long reads + Tigmint (with linked reads) + ARKS (with linked reads)

Based on your results, you could omit the linked read Tigmint run if you're still seeing the contiguity is too low. But I do suggest running the correction/scaffolding with the long reads first and the linked reads next - I like to run scaffolding using evidence in order of length of information (and linked reads tend to provide longer-range information)

Hope that helps - I'm always happy to help out with tips for running our tools!
Lauren

**Comment by aakashsur** [comment]
Excellent! Thanks for the detailed response.
