### ISSUE TITLE
Parameters for corrected ONT reads

### ISSUE THREAD

**Issue by BaxW** [bcgsc/arcs#144]
Hi,
Thanks for all the hard work developing/maintaining this and other helpful tools. 

I noticed in the readme section on running --arks-long mode it says:
"To account for the higher error rates in long reads vs linked reads, we suggest starting with the following values:

m=8-10000
j=0.05
k=20
c=4
l=4
a=0.3 "

Is this assuming raw long reads? If I use Canu-corrected ONT reads, should I adjust these parameters to reflect lower error rate? 

Thanks!

**Comment by lcoombe** [comment]
Hi @BaxW,

Yes, those suggested values are based on using uncorrected ONT reads. We haven't tried running ARKS-long yet using corrected ONT reads, but with more correct reads you could try increasing the `k` value. For context, with short linked reads (ARKS linked read mode), we would usually use k-mer values of between 60-100, but with the ONT reads we found that we needed to lower the k-mer size quite a bit to get good mappings. We also had to decrease the `j` parameter (minimum fraction of read k-mers mapping to a contig end) because of the larger number of error k-mers in ONT reads vs. short reads. So, if you are using more correct reads, you could also try increasing this.

Note that I would expect both of those to lead to more specific mappings, which may help to get rid of noisy mappings, but will also reduce the sensitivity if increased too much. If you do play with the parameters, I'd be very interested to see how your results were impacted!

Hope that helps - thank you for your interest in ARKS-long!
Lauren
