### ISSUE TITLE
arcs-make in bin

### ISSUE THREAD

**Issue by aakashsur** [bcgsc/arcs#145]
It occurred to me while messing around with paths and such, that it might make more sense to have `arcs-make` compile in the `bin` folder after installation rather than the `examples` folder? At least that's where I think I would have expected it along with `makeTSVfile.py` since tigmint has `tigmint-make` and its various python files in the `bin` folder. 

Just a thought, feel free to close.

**Comment by lcoombe** [comment]
Hi @aakashsur,

Yes, you're right that it make more sense to have `arcs-make` in the `bin` folder. Perhaps to retain the copy in both, we could move the file to `bin`, but retain the soft-link in `Examples` so that it won't break anything for those users who have scripts pointing to the script in that location. I'll look at making that tweak later this week!

Thanks!
Lauren

**Comment by lcoombe** [comment]
HI @aakashsur,

I moved `arcs-make` and `makeTSVfile.py` to a `bin` folder (in top-level of repository) in the newest ARCS release (v1.2.3). As I mentioned before, I included soft-links to those files in `Examples` to ensure that nothing should break for users who used the `Examples` path in their previous commands.

Thanks!
