### ISSUE TITLE
fastq formatting barcodes in BX tag

### ISSUE THREAD

**Issue by annaorteu** [bcgsc/arcs#151]
Hello! 
I've been trying to run ARCS using the `make-arcs` command with default options, but I'm not getting any output (i.e. the graph *original.gv  is empty). I've read the issues of people that had the same issue and I'm assuming it's a formatting issue again, but I can't work out where the problem is. I have checked the logs and there is no error message in them. 

the command I use: 
```
nohup nice ~/bin/arcs/bin/arcs-make arcs draft=scaffolds reads=mpheno t=18 & 
```

The fastq.gz file: 
```
$ zcat mpheno.fastq.gz | head
@ST-J00101:183:HGVMLBBXY:8:1126:23003:45502 BX:Z:A00C07B00D27
ATTATGTATGTTTCCCGATAAATGTAAACTAAAAAATTGTCAAAAGTAAACTAGGATGTAAAAAATGCCCCACCATGAATATTATTTTCAATTGCAGCCTATGAGAAATATTGAATCAATATAAAATTTAGATTTTGTCGTTAATTTTAG
+
AAAFFFJJJFJJFJJJJJJJFJFJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJFJJJJFJJJJJJJJJFAFJJJFJA-JJJJJJJJFFFJJJJJFJFJJJJFJ<JJJJJJJJJJ-AFF<AJJF<--AFAJJA-AJFFAJ<FF<7
@ST-J00101:183:HGVMLBBXY:8:1126:23003:45502 BX:Z:A00C07B00D27
AAATAAAAAAAAATAAATTCATAGAAGACACGTTATTCTATAATATATAATATCATATTTATTCATATTATAAAATAGTAAAATTTGTATATAACATTAATTTTTGGTTATTGGTAATTTCTGAAATTAGATTTACAATTTATATAATAC
+
----A-FFFFJ------<-F--<----<-F-------<-----<F-----F-A--A------<-<--<----7---77-<-----7-<-7-----<A---<--7A-------------7---------7A--77----7------7----
@ST-J00101:183:HGVMLBBXY:8:2225:32837:36306 BX:Z:A00C07B00D27
ATTTAAAACTTGGTTTTAAAAAAACTTAATGTAATGTACGTTATATTTTTAATGGAGGTACAGGCGAGTTACATGATACTAAGTTATCTTTACCACCCTTAATGTTTGTAGTACGAGTTGATTCATAATCCCATTCCCGGTTATTAAAAA
```

The fastq files were originally separated so I interleaved them with bbmap's `reformat.sh`. At the end of each read name they had the read pair number `\1` or `\2` but I deleted that as I thought that might be the issue, but didn't solve it. I have had to add the BX:Z tag manually, as I had extracted the reads from a bam file. I have left a space between the read name and the BX tag. 

Do you have any idea where the issue is? I would be super grateful if you could help me.  

Thank you! 
Anna

**Comment by lcoombe** [comment]
Hi Anna,

At first glance, I can't see anything obviously wrong with the formatting of your linked read file. But you are correct that very frequently empty graph files are due to input file formatting issues. Do you think you could provide the full log of your ARCS run so I could take a look? Also, have you been able to successfully run our test demo (https://github.com/bcgsc/arcs/tree/master/Examples) with your installation?

Thanks for your interest in ARCS!
Lauren

**Comment by annaorteu** [comment]
Hi Lauren, 

Thank you for your quick reply! I just ran the demo (arcs_test-demo) and it ran fine (*_original.gv is non empty). 

Just to be sure I re-run arcs with my data after the test run. Here's the log file: 
```
Running: /home/af658/miniconda3/envs/scaffolding_assemblies/bin/LINKS.pl [v1.8.6]
-f scaffolds.renamed.fa
-m 0
-d 4000
-k 15
-e 0.1
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3
-r 
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking sequence target file scaffolds.renamed.fa...ok


Scaffolding mid-point files:
scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.simplepair_checkpoint.tsv
detected; LINKS will skip contig pairing and use info from files instead : Wed 27 Apr 09:49:33 BST 2022

Reading sequences from scaffolds.renamed.fa : Wed 27 Apr 09:49:33 BST 2022

done.
Reading sequence pairs from scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv : Wed 27 Apr 09:49:34 BST 2022

done.
Building scaffolds : Wed 27 Apr 09:49:34 BST 2022

done.
Building .gv graph : Wed 27 Apr 09:49:35 BST 2022


=>Scaffolding ended : Wed 27 Apr 09:49:35 BST 2022
Scaffolds layout in: scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds
Scaffold graph in: scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.gv


=>Making FASTA file : Wed 27 Apr 09:49:35 BST 2022
Scaffolds FASTA in : scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa


=>Wrote correspondence file tracking LINKScontigID <=> OriginalContigNames : scaffolds_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.assembly_correspondence.tsv

Scaffolding executed normally Wed 27 Apr 09:49:37 BST 2022
```

Thank you! 
Anna

**Comment by annaorteu** [comment]
Oh okay. That's good I guess. 

This is an assembly done with SPAdes using the linked reads as short reads. The coverage is really low per individual (~1X) but I have 55 individuals, which I was hoping would be good enough for assembly. I'm interested in this 55 individuals because they are all homozygotes for a certain structural variant (big deletions) at a locus, which I want to assemble. I actually have a really good refernce assembly for this species, but the sequenced individual has the other allele at that locus (with insertions). So I want to use these 55 individuals to see if I can assemble the allele with the deletions.  

So actually I'm only interested in a certain locus of the genome and just wanted to see what the order of the scaffolds is based on these 55 individuals. Does that make sense? Do you think it's feasible and is so, do you have any ideas on how I could achieve that?

Thank you!

**Comment by lcoombe** [comment]
Thanks for the info! 

Having such low coverage per individual, do you expect the coverage of each molecule (ie. the number of reads coming from the same molecule) to be similarly lower than a traditional linked read sequencing experiment? If so, it's possible that the default minimum required aligned read pairs (`c=5`) is too stringent, and you could try lowering that. Depending on the sequence similarity you expect between the assembly and the individuals, you could also lower the sequence identity threshold  `s`.

Since you are just focusing on a particular region, have you thought about doing a targeted scaffolding for that region? Ie. filtering the assembly/reads to just those that map to the particular region? I haven't tried it myself, but thinking you could run ARCS on that targeted set, which may mean that you could be more confident with being less stringent with some parameters.
