### ISSUE TITLE
Parameters for PacBio HiFi data

### ISSUE THREAD

**Issue by romseg** [bcgsc/arcs#155]
Hi,

I would appreciate to know the parameters (-m,-s,-c,-l,-a) you would recommend to run ARCS with PacBio HiFi data. I am thinking on using arcs-make arcs-long. Thank you.

**Comment by lcoombe** [comment]
Hello @romseg,

For running with PacBio HiFi data, I'd suggest starting with the recommended defaults (in the README) for those values - while we did tune the parameters using ONT data, I wouldn't expect the optimal values to be too different with HiFi data.

If you're running in `--arcs-long` mode, you could increase `s` higher to the 80-90 range, since that controls the sequence identity threshold for alignments, and you'd expect that to be higher with HiFi reads. 
If you're running in `--arks-long` mode, you could try increasing the `k` parameter to the 30-40 range, as again you could likely afford this given the higher base quality (increased specificity)

I generally suggest trying different values of `l` and `a` regardless of the mode of ARCS used - for example trying slightly higher values of `a` (max 0.9), and both higher/lower values of `l`. Note that increasing `a` and lowering `l` will make the scaffolding less stringent, so you'd want to be careful to not make them too extreme or risk introducing misassemblies.

I hope that helps - thanks for your interest in ARCS!
Lauren

**Comment by romseg** [comment]
Hi Lauren,

Thanks for your help. I will use your suggestions.

Romulo

**Comment by lcoombe** [comment]
Sounds good - good luck! :)
