### ISSUE TITLE
Incorrect program call?

### ISSUE THREAD

**Issue by jsharbrough** [bcgsc/arcs#161]
Hello,

I am trying to use long reads to scaffold my HiFi contigs (i.e., arcs-make arcs-long), but I'm getting an error when I try to call the menu of the arcs-make tool. Namely, it appears that if I just call arcs-make, the correct program is being called, but if I type:

```
arcs-make -h
```

Then I pull up the help menu for the ```make``` program. Same thing happens if I try to run the full program:

```
arcs-make arcs-long draft=contigs.fasta reads=reads.fastq.gz z=1000
```

I am able to pull up the menu for the ```arcs``` function without issue.

Sorry for what I'm sure is a dumb question. Thanks for any help.

Joel

**Comment by lcoombe** [comment]
Hi @jsharbrough,

So `arcs-make` is a Makefile, which just means that if you specify options like `-h`, it will bring up the make help page instead of the right help page for arcs. If you want to get the help page for arcs, you can run `arcs-make help`, and you should get all the information! 

Also, take a look at this section of the README, which has some examples of proper command formats. For example, you don't include the file extensions in specifying the `draft` and `reads`: https://github.com/bcgsc/arcs#running-arcs-with-long-reads---arcs-long-mode-

I hope that helps - let me know if you have any other questions.
Thank you for your interest in ARCS!
Lauren

**Comment by jsharbrough** [comment]
Ah great, thank you. That worked. I am still unable to get the program to run properly (empty cut250 fastq), but I am at least able to see the help menu. I'll keep cracking. I think it might have something to do with the read names...

**Comment by jsharbrough** [comment]
I did try the demo run, and that also failed to produce the cut250 fastq, so there must be a problem with my installation. Has anybody come across this before? I didn't see anything in the closed issues.

My plan is to start fresh with a new conda environment, but if you have other install tips and tricks, I would greatly appreciate them.

Thanks!

**Comment by lcoombe** [comment]
No, that isn't a problem that I recall coming up previously, and it's hard for me to say where things went wrong without seeing the log - would you be willing to share the standard out/error from the demo run with me? I might be able to help better after seeing that. Other info like the arcs version, etc. would help as well. It is possible that if you have an older version installed with conda that it could cause some issues.
