### ISSUE TITLE
tigmint-make 'missing separator' error

### ISSUE THREAD

**Issue by juliadouglasf** [bcgsc/arcs#164]
I am trying to run Tigmint+ARCS+LINKS using the command `arcs-make arcs-tigmint draft=assembly_name reads=interleaved_reads t=32`. 

I am encountering the error `arcs/bin/tigmint-make:2: *** missing separator. Stop.`, followed by the error `make: *** [arcs/bin/share/arcs-1.2.5-1/bin/arcs-make:224: assembly_name.tigmint.fa] Error 2`.

`arcs/bin/tigmint-make` contains the bash command `make -f arcs/bin/share/tigmint-1.2.10-1/bin/tigmint-make $@`. I looked into `tigmint-make`, but didn't find any syntax-related Makefile errors. I tried commenting out certain sections of `tigmint-make` to see whether I would continue to see the same error. Even after commenting out the entire `tigmint-make` Makefile, I still received the `missing separator` error.

ARCS seems to be calling Tigmint with no problem, given that I see the command in my output: `tigmint tigmint draft=assembly_name reads=interleaved_reads minsize=2000 as=0.65 nm=5 dist=50000 mapq=0 trim=0 span=20 window=1000 t=32`.

Running `tigmint` alone also provokes the `missing separator` error. Again, this error happens even with the entire Makefile commented out.

I installed everything very recently with Conda, and Tigmint is version 1.2.10.

I would appreciate help understanding what is causing this error.

**Comment by lcoombe** [comment]
Hi @juliadouglasf,

Hmm, that's a strange one - I'm having issues reproducing that behaviour on my side.

To confirm, do you see the missing separator error if you run:
```
make -f arcs/bin/share/tigmint-1.2.10-1/bin/tigmint-make version
```

What operating system are you using?

Thank you for your interest in ARCS and Tigmint!
Lauren

**Comment by juliadouglasf** [comment]
Thanks for your response, @lcoombe.

When I run that command, I get the version. `Tigmint 1.2.10`.

I'm using Linux.

**Comment by lcoombe** [comment]
Thanks @juliadouglasf - Ok, that should indicate that the file itself is OK. 
Since we're troubleshooting Tigmint here, could you run the test that we supply in the Tigmint repository? https://github.com/bcgsc/tigmint/tree/master/tests 

There's a README there that describes what to run, etc.  If the test fails, please include the full standard out and error.

**Comment by juliadouglasf** [comment]
The test ran successfully, although the headers for `test_contig.test_linkedreads.as0.65.nm5.molecule.size2000.dist50000.trim0.window1000.span20.breaktigs.fa` are slightly different (e.g., `>test-1::test:0-3051` instead of `>test-1`).

**Comment by lcoombe** [comment]
Ok great, so Tigmint is working fine.

There must be some issue with `arcs-make` then.
You have a couple options:
1) Run Tigmint first, then run ARCS using `arcs-make` (ie. instead of using the `arcs-tigmint` rule)
2) If you want to use `arcs-make` with the `arcs-tigmint` rule, it would help me for you to send me the full standard log and output you get when you launch the job, including the command.

**Comment by lcoombe** [comment]
Hi @juliadouglasf,

I was able to look into the issue further this morning, and think I found the source of your error. I have pushed a fix to master branch (#165) and will be doing a new release (v1.2.6) that incorporates the fix shortly.

**Comment by juliadouglasf** [comment]
Thank you! Version 1.2.6 worked

**Comment by lcoombe** [comment]
Great, glad to hear that!
