### ISSUE TITLE
N50 become smaller while increasing the reads depth

### ISSUE THREAD

**Issue by conniecl** [bcgsc/arcs#18]
Hi,
I'm trying to run ARCS in different depth of 10x reads, and find the scaffold N50 become smaller while increasing the reads depth, here is the details:
![image](https://cloud.githubusercontent.com/assets/18414364/26566019/74b529de-4522-11e7-956d-90e804848563.png)
and here is my command:
```
java -jar trimmomatic-0.33.jar PE -phred33 -threads 4 ${depth}_R1_interleaved.fastq ${depth}_R2_interleaved.fastq ${depth}_trim_1.fq ${depth}_unpair_1.fastq ${depth}_trim_2.fq ${depth}_unpair_2.fq ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:75
bwa mem -t 4 p_ctg.rename.fa ${depth}_trim_1.fq ${depth}_trim_2.fq >${depth}.sam
samtools view -bS ${depth}.sam >${depth}_combine.bam
samtools sort --threads 4 -n ${depth}_combine.bam -o ${depth}_combine.sort.bam
arcs -f p_ctg.rename.fa -a alignments.fof -s 80 -c 2 -l 0 -d 0 -r 0.05 -e 30000 -v 1 -m 20-10000 -b ${depth}_combine
python makeTSVfile.py ${depth}_combine_original.gv ${depth}_combine.tigpair_checkpoint.tsv p_ctg.rename.fa
touch empty.fof
LINKS -f p_ctg.rename.fa -s empty.fof -k 20 -b ${depth}_combine -l 5 -t 2 -a 0.9 -x 1
```
Why this happened? Is there anything wrong with my command? Why the scaffold length become smaller? Hope can get some advice, and thanks in advance.

**Comment by warrenlr** [comment]
no, nothing wrong.  With increased read depth, the scaffold graph increases in complexity, and some merges that were unambiguous at lower read coverage may no longer be possible under the same parameter combination. Although, judging from the N25 length you reported, there are still gains to be had with increased read depth for large scaffolds comprising 25% of your assembly bases. I'd say this is a great result, you have effectively tripled your N50 length! You may also want to report the number of sequences >500bp (or 1kbp) / Number of merges with increased coverage and if you plot depth vs. cumul merges, my intuition is that the number of merges will start to plateau. 

It might be interesting to separate your dataset into three sets of ~50X each, and perform 3 iterative scaffolding rounds, with the same parameters. Because barcodes are re-used, the more data one uses at once with ARCS/LINKS may have unintended consequences, and confound the scaffolding process.

Thank you for sharing your results with us,
Rene

**Comment by conniecl** [comment]
@warrenlr Thanks for your reply, I'll have a try~
