### ISSUE TITLE
Instruction on tuning parameters?

### ISSUE THREAD

**Issue by danshu** [bcgsc/arcs#4]
Hi,

Thanks for you help and I have successfully finished this scaffolding pipeline. Now I want to understand better how Arcs works and what parameters fits my genome. Are there any instructions for this? And may I know when will you paper been published or available online as preprint?

Best,
Danshu

**Comment by danshu** [comment]
I noticed that the gaps added during scaffolding are of small sizes. How does Arcs determine the gap size and Is this size reliable?

**Comment by warrenlr** [comment]
We are working on a manuscript describing parameters, etc, which should be available on a preprint server within a few weeks. The gap size can not be determined since positional information of reads within their molecule of origin is not known. It is arbitrarily set at 10 bp, but it is a placeholder size, as per your intuition.

**Comment by danshu** [comment]
Thanks for your explanation! I will read your manuscript when it is ready.

**Comment by shameem356** [comment]
@warrenlr :did you release please the manuscript ? If yes, please can you share the link ? We are looking to tune the parameters.
