### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by JhinAir** [bcgsc/arcs#41]
Hi,
I got some problems when using arcs:
error: `@SQ     SN:000000F_pilon        LN:62335206': No such file or directory
My command is:
./arcs -f Pilon.fasta -a test.bam -s 98 -c 5 -l 0 -d 0 -r 0.05 -e 30000 -m 20-10000 -v
It gets same errors whenever ALIGNMENTS is sam or bam file. What's going on?

Thank you very much!
Jing

**Comment by JhinAir** [comment]
Even I removed the header of bam, it still gets similar error. What kind of file the arcs requires?

 Options:

   -f, --file=FILE       FASTA file of contig sequences to scaffold [optional]
   -a, --fofName=FILE    text file listing input SAM/BAM filenames

**Comment by lcoombe** [comment]
Hi @JhinAir,
I assume that you solved this for yourself since you closed the issue, but I'll post the answer in case it helps another user. 
The ```-a``` parameter expects a text file listing the paths to the input SAM/BAM files (1 per line). The error is due to you specifying the BAM file directly instead of a text file listing the path to the BAM.

**Comment by JhinAir** [comment]
Dear lcoombe,
Yes, I did such an error. Thank you very much!
Best~
