### ISSUE TITLE
Absolut zero scaffolding

### ISSUE THREAD

**Issue by francicco** [bcgsc/arcs#46]
Hi @lcoombel,

I run my first test, how is it possible that I got zero at all scaffolding. Is something to expect, Is there anything I can do to check to confirm this?

Best
F

**Comment by lcoombe** [comment]
Hi @francicco ,

Yes, it is unusual to get no scaffolding at all. 
Have you tested your ARCS installation using our demo? That can be helpful to see how the pipeline needs to be run, and how files need to be formatted.

Is the graph file output from ARCS empty? That's another common issue that is often due to file formatting (#42, #36, #24). 

I will rename my scaffolds to numbers prior to ARCS, as sometimes the scaffold naming can interfere. If you haven't already, also take a look at Examples/arcs-make, which can be used to run the ARCS pipeline or just show the formatting that ARCS expects.

**Comment by lcoombe** [comment]
@francicco - Take a look at ``runARCSdemo.sh``` (In Examples/arcs_test-demo) -- That should run everything correctly with the appropriate naming/formatting.

The naming of the checkpoint file (generated by makeTSVfile.py) is important -- it must be ```<prefix>.tigpair_checkpoint.tsv```, and ```<prefix>``` must be specified to the ```-b``` parameter of links so it recognizes this input checkpoint file. That's important for LINKS to start at the right place -- you should see something like this in the output of LINKS:
```
Scaffolding mid-point files:
links_c5r0.05e30000-l5-a0.9.tigpair_checkpoint.tsv
links_c5r0.05e30000-l5-a0.9.simplepair_checkpoint.tsv
detected; LINKS will skip contig pairing and use info from files instead: Fri Feb 10 11:36:31 PST 2017
```

For more details, take a look at the example output: Examples/arcs_test-demo/output

**Comment by francicco** [comment]
Hi @lcoombe,

I fixed the my scripts and now the test data is running fine. Not my own data. Maybe the data that I'm running are not compatible to each other. What I'm doing is trying to scaffold a preesisting assembly with my set of 10x linked reads. Or somehow the read format is wrong, again.
This is how they look like:

```
[fc464@login-e-16 Diul]$ zcat Diul.LinkedReads.R1.fastq.gz | head -12
@D00352:461:CCYW4ANXX:4:2301:11920:92828_AAAAAAAACGTAGGAA
AAAATATTAAATAATATAATTTAATAATAATAAAAAAATATATACAATTTAATGGAATAGTTTAAACAAATAATAAAAAAAATATTTAATTAATATTTTCAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFF<FBFFFFFFFFFFFFFFFFF
@D00352:461:CCYW4ANXX:2:2209:19919:18381_AAAAAAAAGAATATAA
TATTAAGGTATATCTCGCTTAAATTGTTATAAAAGTCTAAAGAATACTGACGTACTTACACTGCCTATCCCGCAGGAAATTCAGGAGACTTCCATGAATAAA
+
BFFFFBFBFFBFFBFFB/FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF/F/FF/FFFFF<BFF/BBFFFFBF<BFFF/<BFF<BBBF
@D00352:461:CCYW4ANXX:4:2213:6146:65410_AAAAAAAATGATGATT
AAATATTTCTATTTTGTACTAACAAAATAAAGCGCGACGTTAAGTTTCGCCGTTCAACACGTGTCTCGAATATTGTGCAGGAAGCGTTAAAAACCGGTACAC
+
FFFFFFBFFFFFFFFFFFBBFF<<FFFF<F<B<F/7FFFBFFBFFFFFFF<BFFBFFF<B<<BF/FF<FFFFF<FFFFB<FBFFFFFFFFFFF/B/FFFFFF
[fc464@login-e-16 Diul]$ zcat Diul.LinkedReads.R2.fastq.gz | head -12
@D00352:461:CCYW4ANXX:4:2301:11920:92828_AAAAAAAACGTAGGAA
TTAATATGTTAAATTTATTTATTGAATATCCATCTCCTTATTCACTTTATATTATTTGTATTTTAATATCAATAATTTTCTAAGCGTCCTTTTTACCGACGCCACGCTCCCGCCATGCTCCCTTT
+
BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFF<<FFFBFFFF
@D00352:461:CCYW4ANXX:2:2209:19919:18381_AAAAAAAAGAATATAA
ATATATAGATTTAGGGACATCAACGATGTCGATACTCGAATTAAAGTTCGATACGCTCGTAGAACATCTTGGCGAGTTGCCAGACGCATTGTTAACAAAGCTCTATTTCAAGACTTCTATACTAT
+
BBBBBB/F<FF/FFBB<FFFFFFFF<B<FFF/BFFFFFFFFFBFFFF<BFFFFFFFFB<FFFFFFFFFFFF</F/F7FFFFFBFFBF<FFFFFB7FFFFFFFFFFFFFBFFF<FF<BFFFFFFFF
@D00352:461:CCYW4ANXX:4:2213:6146:65410_AAAAAAAATGATGATT
ATATTAACAACATTATTTAATGCACATACAACATTCAGCCAACGCAGTTTTCAGTGATAGAAACGTAACGATCAATTTCAGGCCAATGAGCTTTAAGGGGATTTAGTGGACTCAATCTCTCGTAA
+
BBBBBFFFF</BFBBBFFFFFB/FFFBFFFFFFFFFFFFFFBFFFFFBFFB/</<F//FFFBBFFFFFFFFBFFFFFFFF/<FFFFFBFFFFFFF<<BFFBFBFF<7<FFFFFFFFFFBFFFFF
```

They look fine to me.

The other thing I'm doing is to use ARCS to scaffold the supernova assembly using the same set of reads. This should in theory improve the more fragmented pseudochromosome. Am I right?

Thanks for your help
F

**Comment by lcoombe** [comment]
Hi @francicco - 

Yes, you can use ARCS to scaffold a supernova assembly using the same linked reads -- We demonstrate this use in our [ARKS paper](https://doi.org/10.1186/s12859-018-2243-x) (ARKS uses the same pairing logic, but uses linked read k-mers instead of read alignments).

As for what is going wrong here, the reads do look to be formatted fine. It is difficult to troubleshoot without more information -- could you provide the commands that you ran, and the logs? Also the first few lines of the FASTA file that you are trying to scaffold? Is the graph file output from ARCS empty or does it have edges?

Also - just so you know - I am on holidays from tomorrow until January 2nd and won't be checking my work e-mails during that time. Just thought I'd mention it in case you wonder why I'm not being as responsive - sorry for any inconvenience!

**Comment by francicco** [comment]
I'm confused now. Should I use ARCS or ARKS?
F

**Comment by francicco** [comment]
Ok, ARCS on Supernova works. I'm gonna try ARKS.
Thanks!
F

**Comment by francicco** [comment]
No problem. I'm also testing ARKS now. Should work too?
F

**Comment by lcoombe** [comment]
@francicco - Sorry for the delay, I just got back from my holidays today.
Yes, I would expect ARCS and ARKS to produce similar results, with perhaps slightly higher contiguity from ARKS (again I'm thinking of Figure 2 from the ARKS paper I referred to above).
Hope the runs were successful!

**Comment by lcoombe** [comment]
I'll close this because it looks like your issue was solved, @francicco. Feel free to open another issue of you have further questions.
