### ISSUE TITLE
Tuning -e parameter

### ISSUE THREAD

**Issue by harish0201** [bcgsc/arcs#47]
Hi,

I'm currently evaluating the scaffolding capacity of Arcs on a genome that I'm working on currently. The genome has been assembled by Canu using RSII reads and is pretty repeat rich. I'm attaching the stats for the assembly (>1kb contigs) here:

num_seqs        26490
sum_len 898447105 (898Mb)
min_len 2002 (2kb)
avg_len 33916.5 (33.91kb)
max_len 1141553 (1.14Mb)
Q1      14867 (IQR1 14.86Kb)
Q2      21309 (IQR2 21.3 Kb)
Q3      32834 (IQR3 32.83Kb)
N50     44537 (44.5Kb)

I'm wondering what should be adequate end-length parameter (-e) for this assembly and how can I tune it. I went through the paper especially through this part and I'm confused:

> Thus, depending on the level of contiguity of the input assembly, adjusting –e to a lower or higher value would account for shorter contigs or focus on longer contigs. When ARCS encounters shorter sequences (less than twice the specified –e length), the length of the head and tail regions are assigned as half the total sequence length. This is important, as the selection of –e will impact how ambiguity is mitigated when creating an edge between any two sequences. 

So, in order to efficiently scaffold my assembly should I drop the -e parameter to the IQR2 length rather than the default 30Kb? How do I tune the parameters for an extremely fragmented assembly?

Harish

**Comment by lcoombe** [comment]
Hi @harish0201,

You could try a few different ```-e``` values, say 10kb, 20kb, 30kb. Since the ARCS step (post-alignment) is quite fast, and your genome appears to be ~900Mb, it would be reasonable to do a sweep and assess how varying ```-e``` impacts the resulting contiguity.
My feeling is that the default ```-e``` will be just fine, since an N50 of 44.5kb is pretty decent, but I'd be interested to see your results. In our assembly projects, we tend to stick with the default ```-e```.

Hope that helps!
Lauren

**Comment by harish0201** [comment]
Dear Lauren,

I will do that and get back,

Thank you!

**Comment by harish0201** [comment]
Dear Lauren,

I will do that and get back,

Thank you!
