### ISSUE TITLE
N50 decreased from Supernova to Tigmint-ARCS-LINKS

### ISSUE THREAD

**Issue by Dharmendra-G-1** [bcgsc/arcs#49]
Hello 
I run the supernova using 
```
supernova run --id=Yuc27M --fastqs=analyzing_fastq --maxreads=1080624478 --localcores=64
```

got the phased fasta file output using following command:
```
supernova mkoutput --style=pseudohap2 --asmdir=EG9-30/outs/assembly --outprefix=/mid_large_2t/second_10xdenova_assembly_EG9_30/EG9-30/newoutput_FASTA/EG9-30_10xgenomics_consensus --index
```

The out is 
```
Yuc27M_10xgenomics_consensus.1.fasta
Yuc27M_10xgenomics_consensus.2.fasta
```

The contigs length wasn't satisfactory so we like to extend the contigs length using Tigmint with ARCS and LINKS

For Tigmint with ARCS and LINKS, first following command were used to get the linked fastq files:
```
longranger basic --id=sample_Yuc27M_1_arcs --fastqs=samples_for_10x --localcores=64
 ```
Reads from longranger basic were renamed as reads.fq.gz and Yuc27M_10xgenomics_consensus.1.fasta from supernova output is renamed as draft.fa. Then arch-make with arcs-tigmint is run using following command: 
```
./arcs-master/Examples/arcs-make arcs-tigmint draft=draft reads=reads
```

First run was using LINKS default a=0.3 and also gave two additional trial using a=0.6 and 0.9 on LINKS a- flag the results are as follows but only increase N50 length from a=0.3 but not from supernova phased fasta output, but the results were quite opposite, it decreased N50 length from original supernova contigs. The abyss-fas for original supernova assembled contigs  Yuc27M_10xgenomics_consensus.1.fasta and three output for LINKS a- 0.3, 0.6, 0.9 are 
draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa
draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.6.scaffolds.fa
draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.9.scaffolds.fa as follows:

```
abyss-fac Yuc27M_10xgenomics_consensus.1.fasta
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
15157	15121	40	815	5973469	18.56e6	34.71e6	22.1e6	59.6e6	2.476e9	Yuc27M_10xgenomics_consensus.1.fasta

abyss-fac draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
15600	15057	92	518	2187088	7011644	16.15e6	9827444	41.75e6	2.476e9	draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa

abyss-fac draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.6.scaffolds.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
15018	14475	84	518	2785433	8790483	17.73e6	10.68e6	41.76e6	2.476e9	draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.6.scaffolds.fa

abyss-fac draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.9.scaffolds.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
14619	14076	72	518	3029632	9622543	21.32e6	12.74e6	52.08e6	2.476e9	draft.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.9.scaffolds.fa
``` 

My question is, if I am missing anything while running the arcs-make with arcs-tigmint that may be shortening the contigs?

I run arch-make with all the default paratment except the above mentioned LINKS a- (0.3/0.6/0.9), 
```
# tigmint Parameters
minsize=2000
as=0.65
nm=5
dist=50000
mapq=0
trim=0
span=20
window=1000

# bwa Parameters
t=40

# ARCS Parameters
c=5
m=50-10000
z=500
s=98
r=0.05
e=30000
D=false
dist_upper=false
d=0
gap=100
B=20
# LINKS Parameters
l=5
a=0.3
```
are there any other parameter I can change that can increase the contigs length and also decrease the missassemblies?

your input is greatly appreciated, 

Thanks

**Comment by lcoombe** [comment]
Hi @Dharmendra-G-1 ,

Thank you for your interest in Tigmint/ARCS!

I have also seen the behaviour that you're describing - Using Tigmint+ARCS on a Supernova assembly decreasing the N50 as compared to the original Supernova assembly. I believe that this is due to the fact that Supernova can introduce very long gaps in the assemblies - over 50kb long. Tigmint's current algorithm will break the assembly at these long gaps. Take a look at the Tigmint paper (https://doi.org/10.1186/s12859-018-2425-6) for more details, but briefly this happens because:
* Tigmint infers molecule extents from the read alignments - Reads of the same barcode will be considered in the same extent/molecule if they align <= dist (default 50kb) apart
* When making decisions about where putative misassemblies are, Tigmint looks for windows of the assembly with very few (< span) spanning molecules.
* If the gap is >50kb, no molecule extents can span the gap, and a cut will be made.

My suggestion would be to try running ARCS without breaking the assembly with Tigmint first. This won't break the assembly at putative misassemblies, but you should see an increase in the overall contiguity. 
If you do want to continue to run Tigmint first, you could play around with reducing the ```span``` parameter.

Hope that helps!

**Comment by lcoombe** [comment]
Closing this for now, but feel free to re-open if you have further questions about this!
