### ISSUE TITLE
arcs-make pipeline query

### ISSUE THREAD

**Issue by plw1080** [bcgsc/arcs#53]
I ran the entire arcs-make (arcs-1.0.5) pipeline on data 
from a small marine organism. The makefile was a great help!

Every stage completed successfully according to the output.

However, there is very little change in the draft genome
after running the pipeline. (See Ml.fa, below, the original
draft genome and Ml_c5_m50-10000_s98...scaffolds.fa the final
output from the pipeline)

Can you suggest some stages of the pipeline I can focus on to
to improve the process.

The reads are 10x linked reads prepared by longranger basic
with this summary:

barcode_diversity,  bc_on_whitelist,  num_read_pairs
188166.842687,  0.896626906719,  110838678

Also included below is a summary of the supernova assembly
of these reads (for iformation only, assembly data not a
part of the the arcs process.)

------------- Ml.fa -------------
number sequences:  5,101
max sequence length:  1,222,598
min sequence length:  987
median sequence length:  1,772
total number residues:  155,875,873
N50:  187314

--Ml_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa --
number sequences:  5,084
max sequence length:  1,222,598
min sequence length:  987
median sequence length:  1,764
total number residues:  155,877,573
N50:  189805

(Suoernova assembly of reads .. for information only!
------------- Mlpseudohap.fasta -------------
number sequences:  25,046
max sequence length:  102,547
min sequence length:  1,000
median sequence length:  3,008
total number residues:  145,149,952
N50:  10665

**Comment by lcoombe** [comment]
Hi @plw1080 ,

Glad to hear that the makefile was helpful!

As for the parameters to play with, I'd start with ```a``` and ```z```. We routinely go up to a=0.9 in our experiments. So, perhaps you could try a=0.3,0.5,0.7,0.9 and z=500, 3000,5000,10000 if you want to do more of a sweep.

Since you have done a Supernova assembly, you could also take a look at the mean molecule size in the ```report.txt``` in the ```outs``` folder of your Supernova run. If you have quite short molecules, for example, you can expect less scaffolding gains using the 10x data.

The last suggestion I'd have for now is that you could try to run Tigmint before ARCS (if you haven't already - this is an option in the makefile). 

Hope that helps!
Lauren

**Comment by plw1080** [comment]
Thank you Lauren.  That is a very big help.  Will try all your suggestions.  Peter
