### ISSUE TITLE
unusual behavior of tigmint

### ISSUE THREAD

**Issue by plw1080** [bcgsc/arcs#55]
Unexpected results from using tigmint with arcs pipeline

arcs alone
==========
Ml_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa -------------
number sequences/scaffolds:  5,084         
max sequence length:  1,222,598
min sequence length:  987
median sequence length:  1,764
total number residues:  155,877,573
Scaffold N50:  189805

arcs with tigmint
=================
Ml.tigmint_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa -------------
number sequences/scaffolds:  14,977
max sequence length:  256,959
min sequence length:   1
median sequence length:  1,469
total number residues:  155,789,698
Scaffold N50:  45459

Why are results with tigmint so very diffrent from arcs alone?

Why does the max scaffold length decrease from over 1,000,000 to 256,000?

Why are there ~3,000 seqs with length < 500 when the min seq length was 987? (Includes five seqs of length 1, three of length 2 !!)

Also the N50 decreases significantly.

**Comment by lcoombe** [comment]
Hi @plw1080 ,

So sorry for the delayed response! 

What assembler did you use to generate the baseline assembly? I have seen examples where using Tigmint on Supernova assemblies can result in a lower contiguity overall due to the very long gaps that Supernova introduces into the scaffolds. Tigmint will cut at very long gaps (Due to the ```--dist``` parameter of ```tigmint-molecule```, which only allows aligning barcoded reads that are at most ```50kb``` apart by default to be considered a single molecule). So for most assemblies, we find that the contiguity of assemblies after Tigmint+ARCS is higher than just ARCS alone, but I have seen that isn't always the case for Supernova assemblies.

As for why you are seeing smaller sequences, that is just because of Tigmint breaking the scaffolds at putative misassemblies prior to subsequent scaffolding with ARCS. For more details of how Tigmint makes the cuts, take a look at the paper (https://doi.org/10.1186/s12859-018-2425-6)

**Comment by plw1080** [comment]
Thank you for your response.  The baseline assembly came from NCBI.  We also have PacBio reads for this organism and are
using Falcon to assemble them.  Then will try to use ARCS again with those results.

**Comment by lcoombe** [comment]
@plw1080 - Sounds good! 
Yes, in the Tigmint paper, we show results of using Tigmint+ARCS on a HG004 Falcon assembly, and we find that ARCS alone yields an NG50 of 18.14 Mbp, whereas we achieve an NG50 of 22.52 Mbp with Tigmint+ARCS. So hopefully you will see similar results with your own Falcon assembly.
Good luck!
