### ISSUE TITLE
Recommendation on multiple lanes

### ISSUE THREAD

**Issue by erondeau** [bcgsc/arcs#56]
Hello ARCS team,

I was wondering if I could get a recommendation on benefits of multiple 10X libraries vs. increased depth per library for ARCS / LINKS scaffolding.

Basically, we would like to increase our scaffolding potential by generating two lanes of 10X data for a genome ~2.5 Gbp (Contig N50 ~100kb). I'm wondering, in your experience, if that is better served with 1) two libraries, each on their own sequencing lane, or 2) 1 library sequenced across two lanes? It would seem to me that option 1 would allow for a greater number of links to span the gap (-l in LINKS), but at the expense of the minimum aligned read pairs per barcode mapping (-c in ARCS). In your opinion, which parameter would be more important in terms of scaffolding, and do you have a recommendation on coverage per library or reads per barcode required to achieve a suitable number of aligned reads (-c in ARCS)? It looks like from the Barcode counts output from ARCS on the first lane we've done, we have an average ~280 reads per barcode.

Thanks for you input and help,

Eric

**Comment by lcoombe** [comment]
Hi Eric,

Do you know what your estimated coverage is per lane? In our tests, we have only used multiple libraries of 10X data for larger (~20GB) genomes, and we have tended to use single libraries for genomes around the size of human - So I don't have any data about single vs multiple library data for genomes of around that size. I would expect you to get decent ARCS scaffolding from 40X-50X sequencing data of 1 library for a genome of that size.

One other consideration is if you are thinking about assembling the reads with Supernova prior to ARCS-scaffolding - Supernova doesn't currently support multiple libraries. You can differentiate the libraries for ARCS, but it requires changing the read group of all the fastqs of one of the libraries (ie. \<barcode\>-1 -> \<barcode\>-2).

It is a bit hard to know too much from the average reads per barcode, since that is likely pulled down by many barcodes with very low multiplicity (error barcodes), and is influenced by the number of molecules in the barcode as well as the read coverage of each molecule. If you wanted to get a sense of your estimated molecule coverage, we often use ```tigmint-molecule``` from the Tigmint repository to do this assessment. If you have a draft assembly, you could align your current reads to that, and run ```tigmint-molecule``` to see the estimated molecule extents for a few of the biggest pieces. Then, you can parse the output BED to get a sense of the current molecule coverage you have. For comparison, we use a human NA24143 chromium dataset for many of our tests, and we found this ~50X dataset to have a median molecule coverage of ~0.185.

Hope that helps!
Lauren
