### ISSUE TITLE
arcs-make command format question

### ISSUE THREAD

**Issue by pal263** [bcgsc/arcs#64]
Hi,

I am new to Arcs and when trying to run the complete pipeline using ./arcs-make as 
./arcs-make arcs-tigmint draft=../final_assembly.fa  reads=../my_reads.fastq.gz

it gives error stating
make: *** No rule to make target `../final_assembly.fa.fa', needed by `../final_assembly.fa.tigmint.fa'.  Stop

I have also given path to all the required softwares like tigmint, links, samtools etc

Kindly Help!!

**Comment by lcoombe** [comment]
Hi @pal263 ,
Instead of using paths like that, soft-link or copy your assembly and reads files into your current working directory.
Also, you don't specify the suffices of the input files for the command.
Once you've made the appropriate soft links, try this command:
```
arcs-make arcs-tigmint draft=final_assembly reads=my_reads
```
Errors like that with Makefiles usually indicate that you have made a small error with how you specify the target and/or input files.
Hope that helps!
Lauren
