### ISSUE TITLE
Polyploid analysis

### ISSUE THREAD

**Issue by trgibbons** [bcgsc/arcs#68]
Greetings from the agricultural genomics community!

I'm currently using some 10x linked-read data to scaffold an allopolyploid plant genome assembly. The 10x software explicitly officially only supports diploid genomes. The documentation for ARCS, LINKS, and Tigmint doesn't explicitly mention any such limitations, but I've found that it's often wise to check  :)

Would anyone on any of these dev team(s) be willing to comment on using these tools for polyploid analysis?

Best,
Ted

**Comment by lcoombe** [comment]
Hi Ted,

Thank you for your interest in ARCS!

We actually haven't ever run ARCS (or LINKS or tigmint) on an allopolyploid assembly in our group before. However, in principle, I think it should be just fine. Our tools don't make any assumptions about the genome ploidy (as I believe Supernova does).
The only consideration I can think of would be how similar the homeologous chromosomes are -- if they have very low sequence divergence, it is possible that the reads could align to the wrong chromosome, thus inducing misassemblies. However, because we filter out mapping quality 0 read for ARCS, and assuming some sequence divergence between the copies, I think it would be OK.

I'd be very interested to hear how our tools perform on this allopolyploid genome!

Lauren
