### ISSUE TITLE
Pick up chromium barcode from BX tag

### ISSUE THREAD

**Issue by johandahlberg** [bcgsc/arcs#7]
Hi!

Thanks for releasing arcs, I've started trying it out and it looks promising. I'm wondering if you would consider picking up the chromium barcode from the `BX` tag instead of from the read name? According to the [10x genomics documentation](https://support.10xgenomics.com/genome-exome/software/pipelines/latest/output/bam) this is where the verified barcode information should be placed.

With kind regards,
Johan Dahlberg

**Comment by jebard** [comment]
Not sure if this was discussed more, but I think this would be a great quality of life improvement. Then you could use the "longranger align" function directly into ARCS from my understanding.

**Comment by sjackman** [comment]
This would be a big improvement for me too. It's also compatible with using `bwa mem -pC` to copy the `BX:Z` tag from the FASTQ header to the SAM tags. I'll make it happen later this week. Bump this issue if you don't hear from me.

**Comment by benvvalk** [comment]
Hi guys, there is a new `--bx` option in ARCS v1.0.2 (just released), or you can also pull it from `master`.  Hope you like it!

**Comment by sjackman** [comment]
Wonderful! Thanks, Ben! Could that option be the default or auto-detected? If the `BX:Z` tag is present, use it by default.

**Comment by benvvalk** [comment]
@sjackman Yep, you are right, that would be better default behaviour.  I will postpone any further fiddling with it until later, though.  (Feel free to fix it in the meantime, if you are so inclined.)

**Comment by sjackman** [comment]
I may just. Thanks for the work, Ben!

**Comment by sjackman** [comment]
I've submitted PR #30 which uses the BX:Z tag if present, and otherwise parses the barcode from the read name.

It also makes the `-f` FASTA file optional. It'll parse the scaffold sizes from the SAM header. If the `-f` option is specified, it checks that the FASTA sequence lengths and SAM header agree. This makes it really easy to pipe the output of the aligner into ARCS (by setting the SAM file argument to `/dev/stdin`) without needing to also specify a FASTA file.
