### ISSUE TITLE
Too much data?

### ISSUE THREAD

**Issue by sunnycqcn** [bcgsc/arcs#75]
Hello Lauren,
Has ARCS data limit? I used  1,213,403,972 reads with arks mode. I did a few times, but I got the same results. If I extract about 1000 reads, the command worked well. The error is as following.
Thanks,
Fuyou

[main] CMD: bwa mem -t40 -pC sk29rl.fa sk29rl.fq.gz
[main] Real time: 61121.256 sec; CPU: 2434403.709 sec
[bam_sort_core] merging from 640 files and 40 in-memory blocks...
[E::hts_open_format] Failed to open file /scratch/sk29rl.sk29rl.sortbx.bam.URTCks.0000.bam
samtools sort: fail to open "/scratch/sk29rl.sk29rl.sortbx.bam.URTCks.0000.bam": No such file or directory
make[1]: *** [sk29rl.sk29rl.sortbx.bam] Error 1
make: *** [sk29rl.tigmint.fa] Error 2

**Comment by warrenlr** [comment]
Hello,
The error you reported is a [bwa] read alignment error, not an ARCS error.
I suggest you consult the bwa manual / github issues to see if a similar error has been reported.

Thanks for using ARCS!

**Comment by sunnycqcn** [comment]
Hello,
Do ARCS need specific version of BWA or any version is ok?
Thanks,
Fuyou

**Comment by warrenlr** [comment]
any versions released in 2016 and after would do.  The error you came across could be due to bwa or samtools.

We have tested the most recent release of ARCS with bwa Version 0.7.17-r1188 and samtools Version: 1.9

In the end, any aligner capable of generating sorted bam files will do. 

Please note that you may also run ARCS without the need to perform read alignments.  To do that, please consult the README.md : Running ARCS in '--arks' mode

hope it helps
Rene

**Comment by sunnycqcn** [comment]
Hello Rene,
Thanks.
I have tested the demo data and small my data set. They worked well without any problem. I will do more.
Thanks,
Fuyou
