### ISSUE TITLE
question about the parameters -m and -d 

### ISSUE THREAD

**Issue by longzhangnation** [bcgsc/arcs#76]
hello,
  I am using ARCS to scaffold my genome with 10X G . When I was reading the ARCS article 'ARCS: scaffolding genome drafts with linked reads ', I was curious about these two parameters. In the essay, it told me that -m represented 'Barcode read frequency range (min-max) ' ,so  what's the effect after tuning the parameter up or dowm ? Similarly ，the meaning of -d is 'Max. degree of nodes in graph ' ,so what's the effect after it is tuned ?
thank you

**Comment by lcoombe** [comment]
Hi @longzhangnation,

`-m` represents the range of accepted barcode multiplicity. This avoids using barcodes for scaffolding that have a very small number of associated reads (so are likely erroneous) and barcodes that have a very large number of associated reads (so likely have a large number of molecules with that barcode). If you want to tune this, you could calculate the number of reads per barcode, and plot the histogram. That would inform where you want to set the acceptable range to get the bulk of the data while not using these extremes. However, usually using the default works well.

`-d` isn't a parameter that I would suggest changing. It works well as the default, and we let the LINKS scaffold layout algorithm traverse the graph vs. cleaning up the graph with ARCS.

Hope that helps, and thank you for your interest in ARCS!
Lauren

**Comment by longzhangnation** [comment]
Thanks for your reply, and i have some doubt about the parameters.
so for the parameter -m , only if one barcode have at least -m read pair  so that it could be thought as an effective barcode . And for the parameter -c , only when we  have at least -c read pair aligened to a     the two sequences ,can we say it builds a connect a link between these sequences. 
And i don't know about the meaning of parameter -d ,what's its use here?

**Comment by lcoombe** [comment]
For `-m`, a given barcode will be used for scaffolding evidence if it has between min-max reads. Otherwise, any alignments/mappings of reads of these barcodes to the contigs are not considered.

For `-c`, in order for a barcode to 'hit' to a contig end, there must be at least `c` read pairs of that barcode mapped to that contig end. So it is referring to amount of read evidence required to say that a barcode hits to a given contig end (this parameter isn't referring to links between sequences). Those barcode hits to the contig ends are then used to create barcode links between sequences.

Again, we don't change `-d`, so I wouldn't be concerned with it. It will filter out nodes in the scaffold graph that have a degree greater than the specified value. But we always keep that parameter as the default value.

**Comment by longzhangnation** [comment]
OK，I see. Thanks for your reply. Right now i know how to distinguish and ues  these parameters.
Hope you have a nice day.

**Comment by lcoombe** [comment]
Glad to hear that helped!
