### ISSUE TITLE
Alignment using longranger and variant calling best practices

### ISSUE THREAD

**Issue by nadiabeyg** [bcgsc/arcs#92]
Dear all,
I am using longranger alignn for mapping tetraploid plant samples (Potato) on my reference.
Here are the statistics of alignment file:
620420547 + 0 in total (QC-passed reads + QC-failed reads)
40338339 + 0 secondary
0 + 0 supplementary
140710457 + 0 duplicates
598029665 + 0 mapped (96.39% : N/A)
580082208 + 0 paired in sequencing
290041104 + 0 read1
290041104 + 0 read2
390667031 + 0 properly paired (67.35% : N/A)
546825133 + 0 with itself and mate mapped
10866193 + 0 singletons (1.87% : N/A)
92225526 + 0 with mate mapped to a different chr
75482652 + 0 with mate mapped to a different chr (mapQ>=5)
For variant calling i am interested in choosing properly paired end reads and in my case its too low (67.35%).
After applying PCR duplicates removal the number of properly paired end reads drop again (282987478).
Why there is low alignment statistics with longranger?
Secondly longranger wgs works for tetraploid samples as well? Because I normaly use freebayes separately to call variants across all samples as I have both diploid and tetraploid samples.
Is there any other better option for aligning 10x linked reads?

**Comment by lcoombe** [comment]
Hi @nadiabeyg ,

For scaffolding draft genome assemblies with ARCS, we generally use `bwa mem`, although some users have `longranger align` and seen decent results (#91). We haven't tried out any other aligners, because both of these seem to be appropriate for the assembly scaffolding problem.

Regarding your questions about `longranger`, it would be better to direct your questions to the developers of that tool suite at 10x Genomics (https://support.10xgenomics.com/genome-exome/software/pipelines/latest/what-is-long-ranger)
