### ISSUE TITLE
Number of Ns

### ISSUE THREAD

**Issue by ViriatoII** [bcgsc/arcs#95]
Hi,

When you scaffold two contigs, do you estimate the number of Ns between them? Or do you put a fixed number?

All the best,
Ricardo

**Comment by lcoombe** [comment]
Hi Ricardo,

You can run ARCS (in default mode or `arks` mode) in either way -- estimating the gap size or using a fixed numbers of Ns.
You can enable the distance estimation by either using `D=true` if you are using the `arcs-make` makefile driver, or `-D` if you are using the `arcs` binary directly.

Hope that helps - thanks for your interest in ARCS!
Lauren

**Comment by ViriatoII** [comment]
This is great, thanks. I see now that you talk about it in the Arks paper. So one more quick question:

Does your distance estimation depend on the molecule size of my 10x libraries? I'm working with plants which always have lower molecule sizes due to the breaking of the cell wall and metabolites.

**Comment by lcoombe** [comment]
Hi Ricardo,

To do the distance estimations, we build up a distribution of intra-contig distances (so known distances) and proportions of shared barcodes between the regions, so it will be specific to your data, including the sizes of your 10x moleucles. So I suppose, yes that distribution will depend on the molecule size of your library, but since it is specific to your input data, you should still be able to get good distance estimations even with smaller molecule sizes.

**Comment by ViriatoII** [comment]
Great, thanks! :)
